name = "danogo2023/bonds/making-ask"
version = "1.0.0"
license = "Apache-2.0"
description = "Aiken contracts for danogo bonds ask making"

[repository]
user = "danogo2023/bonds"
project = "making-ask"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "v1.0.0-bond"
source = "github"
