name = "Danogo2023/bonds-making-ask"
version = "1.0.0"
license = "Apache-2.0"
description = "Aiken contracts for danogo bonds ask making"

[repository]
user = "Danogo2023"
project = "bonds/making-ask"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"

[[dependencies]]
name = "Danogo2023/daken"
version = "features/bond"
source = "github"
