name = 'teko/optim-bond'
version = '0.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project 'teko/optim-bond'"

[repository]
user = 'teko'
project = 'optim-bond'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = '1.0.0'
source = 'github'
