name = 'danogo bonds exchange'
version = '0.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project danogo bonds exchange"

[repository]
user = 'Danogo2023'
project = 'bonds-dex'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = '1.0.0'
source = 'github'
