name = 'Danogo2023/bonds-dex'
version = '1.0.0'
license = 'Apache-2.0'
description = "Aiken contracts for project Danogo2023/bonds-dex"

[repository]
user = 'Danogo2023'
project = 'bonds-dex'
platform = 'github'

[[dependencies]]
name = 'aiken-lang/stdlib'
version = '1.5.0'
source = 'github'
