name = "danogo2023/bonds/dex-making-bid"
version = "1.0.3"
license = "Apache-2.0"
description = "Danogo Bond Exchanges: Bid Making Optim Bond"

[repository]
user = "danogo2023/bonds"
project = "dex-making-bid"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "v1.0.2"
source = "github"
