name = "danogo2023/bonds/optim-making-bid"
version = "1.0.0"
license = "Apache-2.0"
description = "Danogo Bond Exchanges: Bid Making Optim Bond"

[repository]
user = "danogo2023/bonds"
project = "optim-making-bid"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "master"
source = "github"
