name = "Danogo2023/bonds-limit-bid"
version = "1.0.0"
license = "Apache-2.0"
description = "Aiken contracts for danogo bonds bid limit"

[repository]
user = "Danogo2023"
project = "bonds/limit-bid"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"

[[dependencies]]
name = "Danogo2023/bonds-common"
version = "master"
source = "github"
