name = "danogo2023/bonds/limit-bid"
version = "1.0.1"
license = "Apache-2.0"
description = "Aiken contracts for danogo bonds bid limit"

[repository]
user = "danogo2023/bonds"
project = "limit-bid"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "v1.0.1"
source = "github"
