name = "danogo2023/bonds/making-bid"
version = "1.0.0"
license = "Apache-2.0"
description = "Aiken contracts for danogo bonds bid making"

[repository]
user = "danogo2023/bonds"
project = "making-bid"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "master"
source = "github"
