name = "danogo2023/bonds"
version = "1.0.0"
license = "Apache-2.0"
description = "Danogo Bond Borrow Request Validator"

[repository]
user = "danogo2023/bonds"
project = "borrow-request"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "master"
source = "github"
