name = "danogo2023/bonds/optim-limit-ask"
version = "1.0.0"
license = "Apache-2.0"
description = "Danogo Bond Exchanges: Ask Limit Optim Bond"

[repository]
user = "danogo2023/bonds"
project = "optim-limit-ask"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "master"
source = "github"
