name = "danogo2023/bonds/limit-ask"
version = "1.0.0"
license = "Apache-2.0"
description = "Aiken contracts for danogo bonds ask limit"

[repository]
user = "danogo2023/bonds"
project = "limit-ask"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "master"
source = "github"
