name = "vnc4f/danogo-bonds-limit-ask"
version = "1.0.0"
license = "Apache-2.0"
description = "Aiken contracts for danogo bonds ask limit"

[repository]
user = "vnc4f"
project = "danogo-bonds-limit-ask"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"

[[dependencies]]
name = "vnc4f/danogo-bonds-common"
version = "master"
source = "github"
