name = "danogo2023/bonds/dex-limit-ask"
version = "1.0.2"
license = "Apache-2.0"
description = "Danogo Bond Exchanges: Ask Limit Optim Bond"

[repository]
user = "danogo2023/bonds"
project = "dex-limit-ask"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "danogo2023/daken"
version = "v1.0.1"
source = "github"
